### ISSUE TITLE
Input.IsKeyDown()

### ISSUE THREAD

**Issue by JAKETMAN** [SDmodding/Script-Mod#2]
How to use this function, I have tried many ways in other languages but none of them work

**Comment by sneakyevil** [comment]
There is enough explanation on the: https://sneakyevil.gitbook.io/sleeping-dogs-de-script-api/classes/input#.iskeydown
There is enum for all virtualkeys: https://sneakyevil.gitbook.io/sleeping-dogs-de-script-api/enums#virtualkey
Example:
```squirrel
if (Input.IsKeyDown(VirtualKey.W))
{
    // When 'W' key is pressed.
}
```
