### ISSUE TITLE
need function

### ISSUE THREAD

**Issue by JAKETMAN** [SDmodding/Script-Mod#3]
i wanna make a bullet time mod , so i need slow motion and energy value (the yellow one) functions

**Comment by sneakyevil** [comment]
I have no clue why you constantly open issues with something that is already defined...
For slowmotion you can just modify: `Metrics.SimTimeScale` which is documented here: https://sneakyevil.gitbook.io/sleeping-dogs-de-script-api/game-classes/metrics this is literally even used by game itself when you enter slowmotion time.
Other way to achieve slow motion would be to mess with the ActionNodes which are used for animations, but also for triggering certain stuff so there might be even the original slow motion effect.
Also the second part I have no clue what you mean by "energy value"...

**Comment by sneakyevil** [comment]
Closing this, because there is no more information provided.
