### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by JAKETMAN** [SDmodding/Script-Mod#4]
this code didnt send error but not work
if (Input.IsKeyDown(VirtualKey.H))
{
    SimCharacter.Create(Hash.Get("object-physical-character-Thug_18k_brawler"), SimCharacter.GetLocalPlayer().GetPosition(), 0.0);
}

**Comment by sneakyevil** [comment]
I don't see much more information how you handle it in the script? If you just put it in the script file and expect it to work then please read properly the documentation... Your need to be inside https://sneakyevil.gitbook.io/sleeping-dogs-de-script-api/callbacks/ongameupdate and IsKeyDown will return true whole time you hold the key so when you hold on the key for even 1 second you gonna spawn more than 60 characters which can also result in game crash.
