### ISSUE TITLE
a question or a request

### ISSUE THREAD

**Issue by JAKETMAN** [SDmodding/Script-Mod#7]
Is there a way to replace the player's animation with other npc's

**Comment by sneakyevil** [comment]
No, and there probably won't be. All animations are under playerbehaviour with action nodes there isn't anyway to modify that because it's literally unknown file format with no information.

**Comment by JAKETMAN** [comment]
No way to convert those bins to hkx?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月30日(星期天) 凌晨2:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SDmodding/Script-Mod] a question or a request (Issue #7)






没有可能也不会有。所有的动画都是在玩家行为和动作节点下进行的，无论如何都无法修改，因为它是一个没有任何信息的未知文件格式。

—
直接回复此邮件，在GitHub上查看，或取消订阅.
***@***.***与&gt;.

**Comment by sneakyevil** [comment]
Behaviour files are not hkx, they're custom UFG file format that is connected to individual nodes what action they take and what action ID to playback.
